[package]
name = "weird"
version = "0.1.0"
description = "Local-first website generator."
authors = ["Noah Too <krivahtoo@gmail.com>"]
license = "MIT"
repository = "https://github.com/commune-os/weird-tauri"
default-run = "weird"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }
walkdir = "2.3.3"
zip = { version = "0.6.4", default-features = false, features = ["deflate", "time"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.3", features = ["dialog"] }
log = "0.4"
walkdir = "2.3.3"

[dependencies.zip]
version = "0.6.4"
default-features = false
features = ["deflate", "time"]

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
